[package]
name = "carnetrxaptos"
version = "0.0.1"
upgrade_policy = "compatible"

[addresses]
carnetrxaptos = "_"

[dependencies]
AptosFramework = { git = "https://github.com/aptos-labs/aptos-core.git", rev = "randomnet", subdir = "aptos-move/framework/aptos-framework" }
AptosTokenObjects = { git = "https://github.com/aptos-labs/aptos-core.git", rev = "randomnet", subdir = "aptos-move/framework/aptos-token-objects" }

# For use when developing and testing this module
[dev-addresses]
aptogotchi = "0x100"